# API - Application Programming Interface

# JSON - JavaScript Object Notation

In [48]:
import requests
import pandas as pd
import acquire

In [2]:
url = 'https://swapi.dev/api/people/1/'

In [3]:
response = requests.get(url)

In [4]:
response.text

'{"name":"Luke Skywalker","height":"172","mass":"77","hair_color":"blond","skin_color":"fair","eye_color":"blue","birth_year":"19BBY","gender":"male","homeworld":"https://swapi.dev/api/planets/1/","films":["https://swapi.dev/api/films/1/","https://swapi.dev/api/films/2/","https://swapi.dev/api/films/3/","https://swapi.dev/api/films/6/"],"species":[],"vehicles":["https://swapi.dev/api/vehicles/14/","https://swapi.dev/api/vehicles/30/"],"starships":["https://swapi.dev/api/starships/12/","https://swapi.dev/api/starships/22/"],"created":"2014-12-09T13:50:51.644000Z","edited":"2014-12-20T21:17:56.891000Z","url":"https://swapi.dev/api/people/1/"}'

In [5]:
json = response.json() #setting json to variable and then calling the keys
json.keys()

dict_keys(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color', 'birth_year', 'gender', 'homeworld', 'films', 'species', 'vehicles', 'starships', 'created', 'edited', 'url'])

In [6]:
json['starships']

['https://swapi.dev/api/starships/12/', 'https://swapi.dev/api/starships/22/']

In [7]:
for ship in json['starships']: #for loop that looks at each object in the list and prints the object
    response = requests.get(ship)
    
    print(response.json()['name'])

X-wing
Imperial shuttle

In [8]:
base_url = 'https://swapi.dev/api/people/'

In [9]:
response = requests.get(base_url)
response.json()

{'count': 82,
 'next': 'https://swapi.dev/api/people/?page=2',
 'previous': None,
 'results': [{'name': 'Luke Skywalker',
   'height': '172',
   'mass': '77',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '19BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/14/',
    'https://swapi.dev/api/vehicles/30/'],
   'starships': ['https://swapi.dev/api/starships/12/',
    'https://swapi.dev/api/starships/22/'],
   'created': '2014-12-09T13:50:51.644000Z',
   'edited': '2014-12-20T21:17:56.891000Z',
   'url': 'https://swapi.dev/api/people/1/'},
  {'name': 'C-3PO',
   'height': '167',
   'mass': '75',
   'hair_color': 'n/a',
   'skin_color': 'gold',
   'eye_color': 'yellow',
   'birth_year': '112BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:10:51.357000Z',
   'edited': '2014-12-20T21:17:50.309000Z',
   'url': 'https://swapi.dev/api/people/2/'},
  {'name': 'R2-D2',
   'height': '96',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, blue',
   'eye_color': 'red',
   'birth_year': '33BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/8/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:11:50.376000Z',
   'edited': '2014-12-20T21:17:50.311000Z',
   'url': 'https://swapi.dev/api/people/3/'},
  {'name': 'Darth Vader',
   'height': '202',
   'mass': '136',
   'hair_color': 'none',
   'skin_color': 'white',
   'eye_color': 'yellow',
   'birth_year': '41.9BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.dev/api/starships/13/'],
   'created': '2014-12-10T15:18:20.704000Z',
   'edited': '2014-12-20T21:17:50.313000Z',
   'url': 'https://swapi.dev/api/people/4/'},
  {'name': 'Leia Organa',
   'height': '150',
   'mass': '49',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '19BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.dev/api/planets/2/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/30/'],
   'starships': [],
   'created': '2014-12-10T15:20:09.791000Z',
   'edited': '2014-12-20T21:17:50.315000Z',
   'url': 'https://swapi.dev/api/people/5/'},
  {'name': 'Owen Lars',
   'height': '178',
   'mass': '120',
   'hair_color': 'brown, grey',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '52BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:52:14.024000Z',
   'edited': '2014-12-20T21:17:50.317000Z',
   'url': 'https://swapi.dev/api/people/6/'},
  {'name': 'Beru Whitesun lars',
   'height': '165',
   'mass': '75',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '47BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:53:41.121000Z',
   'edited': '2014-12-20T21:17:50.319000Z',
   'url': 'https://swapi.dev/api/people/7/'},
  {'name': 'R5-D4',
   'height': '97',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, red',
   'eye_color': 'red',
   'birth_year': 'unknown',
   'gender': 'n/a',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/'],
   'species': ['https://swapi.dev/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:57:50.959000Z',
   'edited': '2014-12-20T21:17:50.321000Z',
   'url': 'https://swapi.dev/api/people/8/'},
  {'name': 'Biggs Darklighter',
   'height': '183',
   'mass': '84',
   'hair_color': 'black',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '24BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/1/',
   'films': ['https://swapi.dev/api/films/1/'],
   'species': [],
   'vehicles': [],
   'starships': ['https://swapi.dev/api/starships/12/'],
   'created': '2014-12-10T15:59:50.509000Z',
   'edited': '2014-12-20T21:17:50.323000Z',
   'url': 'https://swapi.dev/api/people/9/'},
  {'name': 'Obi-Wan Kenobi',
   'height': '182',
   'mass': '77',
   'hair_color': 'auburn, white',
   'skin_color': 'fair',
   'eye_color': 'blue-gray',
   'birth_year': '57BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.dev/api/planets/20/',
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'species': [],
   'vehicles': ['https://swapi.dev/api/vehicles/38/'],
   'starships': ['https://swapi.dev/api/starships/48/',
    'https://swapi.dev/api/starships/59/',
    'https://swapi.dev/api/starships/64/',
    'https://swapi.dev/api/starships/65/',
    'https://swapi.dev/api/starships/74/'],
   'created': '2014-12-10T16:16:29.192000Z',
   'edited': '2014-12-20T21:17:50.325000Z',
   'url': 'https://swapi.dev/api/people/10/'}]}

In [10]:
names = []
height = []
mass = []

for i in range(1, 10):
    new_url = base_url + f'{i}/'
    response = requests.get(new_url)
    json = response.json()
    names.append(json['name'])
    height.append(json['height'])
    mass.append(json['mass'])
    
len(names), len(height), len(mass)

(9, 9, 9)

In [11]:
pd.DataFrame({'name': names, 
              'height': height, 
              'mass': mass})

                 name height mass
0      Luke Skywalker    172   77
1               C-3PO    167   75
2               R2-D2     96   32
3         Darth Vader    202  136
4         Leia Organa    150   49
5           Owen Lars    178  120
6  Beru Whitesun lars    165   75
7               R5-D4     97   32
8   Biggs Darklighter    183   84

In [12]:
url = 'https://swapi.dev/api/people/'

In [13]:
response = requests.get(url)
response

In [14]:
data = response.json() #turned request into json

In [15]:
data.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [16]:
df = pd.DataFrame(data['results']) # turn page 1 json into df

In [17]:
df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/
5,Owen Lars,178,120,"brown, grey",light,blue,52BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T15:52:14.024000Z,2014-12-20T21:17:50.317000Z,https://swapi.dev/api/people/6/
6,Beru Whitesun lars,165,75,brown,light,blue,47BBY,female,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T15:53:41.121000Z,2014-12-20T21:17:50.319000Z,https://swapi.dev/api/people/7/
7,R5-D4,97,32,n/a,"white, red",red,unknown,n/a,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/films/1/],[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:57:50.959000Z,2014-12-20T21:17:50.321000Z,https://swapi.dev/api/people/8/
8,Biggs Darklighter,183,84,black,light,brown,24BBY,male,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/films/1/],[],[],[https://swapi.dev/api/starships/12/],2014-12-10T15:59:50.509000Z,2014-12-20T21:17:50.323000Z,https://swapi.dev/api/people/9/
9,Obi-Wan Kenobi,182,77,"auburn, white",fair,blue-gray,57BBY,male,https://swapi.dev/api/planets/20/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/38/],"[https://swapi.dev/api/starships/48/, https://...",2014-12-10T16:16:29.192000Z,2014-12-20T21:17:50.325000Z,https://swapi.dev/api/people/10/

In [18]:
page_two = requests.get(data['next']) #calling page 2

In [19]:
two = page_two.json() #turn page 2 into df

In [20]:
two.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [21]:
df2 = pd.DataFrame(two['results']) # turn two['results'] into df

In [22]:
df2

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Anakin Skywalker,188,84,blond,fair,blue,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/4/, https://swapi...",[],"[https://swapi.dev/api/vehicles/44/, https://s...","[https://swapi.dev/api/starships/39/, https://...",2014-12-10T16:20:44.310000Z,2014-12-20T21:17:50.327000Z,https://swapi.dev/api/people/11/
1,Wilhuff Tarkin,180,unknown,"auburn, grey",fair,blue,64BBY,male,https://swapi.dev/api/planets/21/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-10T16:26:56.138000Z,2014-12-20T21:17:50.330000Z,https://swapi.dev/api/people/12/
2,Chewbacca,228,112,brown,unknown,blue,200BBY,male,https://swapi.dev/api/planets/14/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/3/],[https://swapi.dev/api/vehicles/19/],"[https://swapi.dev/api/starships/10/, https://...",2014-12-10T16:42:45.066000Z,2014-12-20T21:17:50.332000Z,https://swapi.dev/api/people/13/
3,Han Solo,180,80,brown,fair,brown,29BBY,male,https://swapi.dev/api/planets/22/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],"[https://swapi.dev/api/starships/10/, https://...",2014-12-10T16:49:14.582000Z,2014-12-20T21:17:50.334000Z,https://swapi.dev/api/people/14/
4,Greedo,173,74,n/a,green,black,44BBY,male,https://swapi.dev/api/planets/23/,[https://swapi.dev/api/films/1/],[https://swapi.dev/api/species/4/],[],[],2014-12-10T17:03:30.334000Z,2014-12-20T21:17:50.336000Z,https://swapi.dev/api/people/15/
5,Jabba Desilijic Tiure,175,"1,358",n/a,"green-tan, brown",orange,600BBY,hermaphrodite,https://swapi.dev/api/planets/24/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/5/],[],[],2014-12-10T17:11:31.638000Z,2014-12-20T21:17:50.338000Z,https://swapi.dev/api/people/16/
6,Wedge Antilles,170,77,brown,fair,hazel,21BBY,male,https://swapi.dev/api/planets/22/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/14/],[https://swapi.dev/api/starships/12/],2014-12-12T11:08:06.469000Z,2014-12-20T21:17:50.341000Z,https://swapi.dev/api/people/18/
7,Jek Tono Porkins,180,110,brown,fair,blue,unknown,male,https://swapi.dev/api/planets/26/,[https://swapi.dev/api/films/1/],[],[],[https://swapi.dev/api/starships/12/],2014-12-12T11:16:56.569000Z,2014-12-20T21:17:50.343000Z,https://swapi.dev/api/people/19/
8,Yoda,66,17,white,green,brown,896BBY,male,https://swapi.dev/api/planets/28/,"[https://swapi.dev/api/films/2/, https://swapi...",[https://swapi.dev/api/species/6/],[],[],2014-12-15T12:26:01.042000Z,2014-12-20T21:17:50.345000Z,https://swapi.dev/api/people/20/
9,Palpatine,170,75,grey,pale,yellow,82BBY,male,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/2/, https://swapi...",[],[],[],2014-12-15T12:48:05.971000Z,2014-12-20T21:17:50.347000Z,https://swapi.dev/api/people/21/

In [23]:
df = pd.concat([df, df2]) #put page 1 and pg 2 df together

In [24]:
response = requests.get(two['next']) #call page 3
data = response.json()
df3 = pd.DataFrame(data['results'])

In [25]:
df = pd.concat([df,df3]) # concat to df

In [26]:
response = requests.get(data['next']) # call page 4
data = response.json()
df4 = pd.DataFrame(data['results'])
df = pd.concat([df,df4])

In [27]:
response = requests.get(data['next']) #call page 5
data = response.json()
df5 = pd.DataFrame(data['results'])
df = pd.concat([df,df5])

In [28]:
response = requests.get(data['next']) #call pg 6
data = response.json()
df6 = pd.DataFrame(data['results'])
df = pd.concat([df,df6])

In [29]:
response = requests.get(data['next']) #call pg 7
data = response.json()
df7 = pd.DataFrame(data['results'])
df = pd.concat([df,df7])

In [30]:
response = requests.get(data['next']) #call pg 8
data = response.json()
df8 = pd.DataFrame(data['results'])
df = pd.concat([df,df8])

In [31]:
response = requests.get(data['next']) #call pg 9
data = response.json()
df9 = pd.DataFrame(data['results'])
df = pd.concat([df,df9])

In [32]:
df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/
8,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/
9,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/
0,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/
1,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/

In [33]:
data['next']

In [34]:
starships = pd.DataFrame(df['starships']) # turn starship column into its own df

In [35]:
starships = starships.reset_index()     #reseting index to be 1 - 82

In [36]:
starships = starships.drop(columns = ['index']) #dropped column that listed index as 1-9 repeating

In [37]:
starships

                                            starships
0   [https://swapi.dev/api/starships/12/, https://...
1                                                  []
2                                                  []
3               [https://swapi.dev/api/starships/13/]
4                                                  []
..                                                ...
77              [https://swapi.dev/api/starships/74/]
78                                                 []
79                                                 []
80                                                 []
81                                                 []

[82 rows x 1 columns]

In [38]:
starships_df = [] #for loop that calls API for every REST in starships column
for i in range(0, 82):
    length = len(starships['starships'].loc[i])
    if len(starships['starships'].loc[i]) == 1:
        data = requests.get(starships['starships'].loc[i][0])
        datajson = data.json()
        starships_df.append(datajson)
    else:
        for z in range(0, length):
                       data = requests.get(starships['starships'].loc[i][z])
                       datajson = data.json()
                       starships_df.append(datajson)

starships_df

[{'name': 'X-wing',
  'model': 'T-65 X-wing',
  'manufacturer': 'Incom Corporation',
  'cost_in_credits': '149999',
  'length': '12.5',
  'max_atmosphering_speed': '1050',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '110',
  'consumables': '1 week',
  'hyperdrive_rating': '1.0',
  'MGLT': '100',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/9/',
   'https://swapi.dev/api/people/18/',
   'https://swapi.dev/api/people/19/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-12T11:19:05.340000Z',
  'edited': '2014-12-20T21:23:49.886000Z',
  'url': 'https://swapi.dev/api/starships/12/'},
 {'name': 'Imperial shuttle',
  'model': 'Lambda-class T-4a shuttle',
  'manufacturer': 'Sienar Fleet Systems',
  'cost_in_credits': '240000',
  'length': '20',
  'max_atmosphering_speed': '850',
  'crew': '6',
  'passengers': '20',
  'cargo_capacity': '80000',
  'consumables': '2 months',
  'hyperdrive_rating': '1.0',
  'MGLT': '50',
  'starship_class': 'Armed government transport',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/'],
  'films': ['https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-15T13:04:47.235000Z',
  'edited': '2014-12-20T21:23:49.900000Z',
  'url': 'https://swapi.dev/api/starships/22/'},
 {'name': 'TIE Advanced x1',
  'model': 'Twin Ion Engine Advanced x1',
  'manufacturer': 'Sienar Fleet Systems',
  'cost_in_credits': 'unknown',
  'length': '9.2',
  'max_atmosphering_speed': '1200',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '150',
  'consumables': '5 days',
  'hyperdrive_rating': '1.0',
  'MGLT': '105',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/4/'],
  'films': ['https://swapi.dev/api/films/1/'],
  'created': '2014-12-12T11:21:32.991000Z',
  'edited': '2014-12-20T21:23:49.889000Z',
  'url': 'https://swapi.dev/api/starships/13/'},
 {'name': 'X-wing',
  'model': 'T-65 X-wing',
  'manufacturer': 'Incom Corporation',
  'cost_in_credits': '149999',
  'length': '12.5',
  'max_atmosphering_speed': '1050',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '110',
  'consumables': '1 week',
  'hyperdrive_rating': '1.0',
  'MGLT': '100',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/9/',
   'https://swapi.dev/api/people/18/',
   'https://swapi.dev/api/people/19/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-12T11:19:05.340000Z',
  'edited': '2014-12-20T21:23:49.886000Z',
  'url': 'https://swapi.dev/api/starships/12/'},
 {'name': 'Jedi starfighter',
  'model': 'Delta-7 Aethersprite-class interceptor',
  'manufacturer': 'Kuat Systems Engineering',
  'cost_in_credits': '180000',
  'length': '8',
  'max_atmosphering_speed': '1150',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '60',
  'consumables': '7 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/58/'],
  'films': ['https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T17:35:23.906000Z',
  'edited': '2014-12-20T21:23:49.930000Z',
  'url': 'https://swapi.dev/api/starships/48/'},
 {'name': 'Trade Federation cruiser',
  'model': 'Providence-class carrier/destroyer',
  'manufacturer': 'Rendili StarDrive, Free Dac Volunteers Engineering corps.',
  'cost_in_credits': '125000000',
  'length': '1088',
  'max_atmosphering_speed': '1050',
  'crew': '600',
  'passengers': '48247',
  'cargo_capacity': '50000000',
  'consumables': '4 years',
  'hyperdrive_rating': '1.5',
  'MGLT': 'unknown',
  'starship_class': 'capital ship',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/11/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:40:21.902000Z',
  'edited': '2014-12-20T21:23:49.941000Z',
  'url': 'https://swapi.dev/api/starships/59/'},
 {'name': 'Naboo star skiff',
  'model': 'J-type star skiff',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated',
  'cost_in_credits': 'unknown',
  'length': '29.2',
  'max_atmosphering_speed': '1050',
  'crew': '3',
  'passengers': '3',
  'cargo_capacity': 'unknown',
  'consumables': 'unknown',
  'hyperdrive_rating': '0.5',
  'MGLT': 'unknown',
  'starship_class': 'yacht',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/35/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:55:15.396000Z',
  'edited': '2014-12-20T21:23:49.948000Z',
  'url': 'https://swapi.dev/api/starships/64/'},
 {'name': 'Jedi Interceptor',
  'model': 'Eta-2 Actis-class light interceptor',
  'manufacturer': 'Kuat Systems Engineering',
  'cost_in_credits': '320000',
  'length': '5.47',
  'max_atmosphering_speed': '1500',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '60',
  'consumables': '2 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'starfighter',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/11/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:56:57.468000Z',
  'edited': '2014-12-20T21:23:49.951000Z',
  'url': 'https://swapi.dev/api/starships/65/'},
 {'name': 'Belbullab-22 starfighter',
  'model': 'Belbullab-22 starfighter',
  'manufacturer': 'Feethan Ottraw Scalable Assemblies',
  'cost_in_credits': '168000',
  'length': '6.71',
  'max_atmosphering_speed': '1100',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '140',
  'consumables': '7 days',
  'hyperdrive_rating': '6',
  'MGLT': 'unknown',
  'starship_class': 'starfighter',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/79/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T20:38:05.031000Z',
  'edited': '2014-12-20T21:23:49.959000Z',
  'url': 'https://swapi.dev/api/starships/74/'},
 {'name': 'Naboo fighter',
  'model': 'N-1 starfighter',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps',
  'cost_in_credits': '200000',
  'length': '11',
  'max_atmosphering_speed': '1100',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '65',
  'consumables': '7 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/11/',
   'https://swapi.dev/api/people/35/',
   'https://swapi.dev/api/people/60/'],
  'films': ['https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/'],
  'created': '2014-12-19T17:39:17.582000Z',
  'edited': '2014-12-20T21:23:49.917000Z',
  'url': 'https://swapi.dev/api/starships/39/'},
 {'name': 'Trade Federation cruiser',
  'model': 'Providence-class carrier/destroyer',
  'manufacturer': 'Rendili StarDrive, Free Dac Volunteers Engineering corps.',
  'cost_in_credits': '125000000',
  'length': '1088',
  'max_atmosphering_speed': '1050',
  'crew': '600',
  'passengers': '48247',
  'cargo_capacity': '50000000',
  'consumables': '4 years',
  'hyperdrive_rating': '1.5',
  'MGLT': 'unknown',
  'starship_class': 'capital ship',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/11/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:40:21.902000Z',
  'edited': '2014-12-20T21:23:49.941000Z',
  'url': 'https://swapi.dev/api/starships/59/'},
 {'name': 'Jedi Interceptor',
  'model': 'Eta-2 Actis-class light interceptor',
  'manufacturer': 'Kuat Systems Engineering',
  'cost_in_credits': '320000',
  'length': '5.47',
  'max_atmosphering_speed': '1500',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '60',
  'consumables': '2 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'starfighter',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/11/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:56:57.468000Z',
  'edited': '2014-12-20T21:23:49.951000Z',
  'url': 'https://swapi.dev/api/starships/65/'},
 {'name': 'Millennium Falcon',
  'model': 'YT-1300 light freighter',
  'manufacturer': 'Corellian Engineering Corporation',
  'cost_in_credits': '100000',
  'length': '34.37',
  'max_atmosphering_speed': '1050',
  'crew': '4',
  'passengers': '6',
  'cargo_capacity': '100000',
  'consumables': '2 months',
  'hyperdrive_rating': '0.5',
  'MGLT': '75',
  'starship_class': 'Light freighter',
  'pilots': ['https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/',
   'https://swapi.dev/api/people/25/',
   'https://swapi.dev/api/people/31/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-10T16:59:45.094000Z',
  'edited': '2014-12-20T21:23:49.880000Z',
  'url': 'https://swapi.dev/api/starships/10/'},
 {'name': 'Imperial shuttle',
  'model': 'Lambda-class T-4a shuttle',
  'manufacturer': 'Sienar Fleet Systems',
  'cost_in_credits': '240000',
  'length': '20',
  'max_atmosphering_speed': '850',
  'crew': '6',
  'passengers': '20',
  'cargo_capacity': '80000',
  'consumables': '2 months',
  'hyperdrive_rating': '1.0',
  'MGLT': '50',
  'starship_class': 'Armed government transport',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/'],
  'films': ['https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-15T13:04:47.235000Z',
  'edited': '2014-12-20T21:23:49.900000Z',
  'url': 'https://swapi.dev/api/starships/22/'},
 {'name': 'Millennium Falcon',
  'model': 'YT-1300 light freighter',
  'manufacturer': 'Corellian Engineering Corporation',
  'cost_in_credits': '100000',
  'length': '34.37',
  'max_atmosphering_speed': '1050',
  'crew': '4',
  'passengers': '6',
  'cargo_capacity': '100000',
  'consumables': '2 months',
  'hyperdrive_rating': '0.5',
  'MGLT': '75',
  'starship_class': 'Light freighter',
  'pilots': ['https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/',
   'https://swapi.dev/api/people/25/',
   'https://swapi.dev/api/people/31/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-10T16:59:45.094000Z',
  'edited': '2014-12-20T21:23:49.880000Z',
  'url': 'https://swapi.dev/api/starships/10/'},
 {'name': 'Imperial shuttle',
  'model': 'Lambda-class T-4a shuttle',
  'manufacturer': 'Sienar Fleet Systems',
  'cost_in_credits': '240000',
  'length': '20',
  'max_atmosphering_speed': '850',
  'crew': '6',
  'passengers': '20',
  'cargo_capacity': '80000',
  'consumables': '2 months',
  'hyperdrive_rating': '1.0',
  'MGLT': '50',
  'starship_class': 'Armed government transport',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/'],
  'films': ['https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-15T13:04:47.235000Z',
  'edited': '2014-12-20T21:23:49.900000Z',
  'url': 'https://swapi.dev/api/starships/22/'},
 {'name': 'X-wing',
  'model': 'T-65 X-wing',
  'manufacturer': 'Incom Corporation',
  'cost_in_credits': '149999',
  'length': '12.5',
  'max_atmosphering_speed': '1050',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '110',
  'consumables': '1 week',
  'hyperdrive_rating': '1.0',
  'MGLT': '100',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/9/',
   'https://swapi.dev/api/people/18/',
   'https://swapi.dev/api/people/19/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-12T11:19:05.340000Z',
  'edited': '2014-12-20T21:23:49.886000Z',
  'url': 'https://swapi.dev/api/starships/12/'},
 {'name': 'X-wing',
  'model': 'T-65 X-wing',
  'manufacturer': 'Incom Corporation',
  'cost_in_credits': '149999',
  'length': '12.5',
  'max_atmosphering_speed': '1050',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '110',
  'consumables': '1 week',
  'hyperdrive_rating': '1.0',
  'MGLT': '100',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/1/',
   'https://swapi.dev/api/people/9/',
   'https://swapi.dev/api/people/18/',
   'https://swapi.dev/api/people/19/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-12T11:19:05.340000Z',
  'edited': '2014-12-20T21:23:49.886000Z',
  'url': 'https://swapi.dev/api/starships/12/'},
 {'name': 'Slave 1',
  'model': 'Firespray-31-class patrol and attack',
  'manufacturer': 'Kuat Systems Engineering',
  'cost_in_credits': 'unknown',
  'length': '21.5',
  'max_atmosphering_speed': '1000',
  'crew': '1',
  'passengers': '6',
  'cargo_capacity': '70000',
  'consumables': '1 month',
  'hyperdrive_rating': '3.0',
  'MGLT': '70',
  'starship_class': 'Patrol craft',
  'pilots': ['https://swapi.dev/api/people/22/'],
  'films': ['https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/5/'],
  'created': '2014-12-15T13:00:56.332000Z',
  'edited': '2014-12-20T21:23:49.897000Z',
  'url': 'https://swapi.dev/api/starships/21/'},
 {'name': 'Millennium Falcon',
  'model': 'YT-1300 light freighter',
  'manufacturer': 'Corellian Engineering Corporation',
  'cost_in_credits': '100000',
  'length': '34.37',
  'max_atmosphering_speed': '1050',
  'crew': '4',
  'passengers': '6',
  'cargo_capacity': '100000',
  'consumables': '2 months',
  'hyperdrive_rating': '0.5',
  'MGLT': '75',
  'starship_class': 'Light freighter',
  'pilots': ['https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/',
   'https://swapi.dev/api/people/25/',
   'https://swapi.dev/api/people/31/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-10T16:59:45.094000Z',
  'edited': '2014-12-20T21:23:49.880000Z',
  'url': 'https://swapi.dev/api/starships/10/'},
 {'name': 'A-wing',
  'model': 'RZ-1 A-wing Interceptor',
  'manufacturer': 'Alliance Underground Engineering, Incom Corporation',
  'cost_in_credits': '175000',
  'length': '9.6',
  'max_atmosphering_speed': '1300',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '40',
  'consumables': '1 week',
  'hyperdrive_rating': '1.0',
  'MGLT': '120',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/29/'],
  'films': ['https://swapi.dev/api/films/3/'],
  'created': '2014-12-18T11:16:34.542000Z',
  'edited': '2014-12-20T21:23:49.907000Z',
  'url': 'https://swapi.dev/api/starships/28/'},
 {'name': 'Millennium Falcon',
  'model': 'YT-1300 light freighter',
  'manufacturer': 'Corellian Engineering Corporation',
  'cost_in_credits': '100000',
  'length': '34.37',
  'max_atmosphering_speed': '1050',
  'crew': '4',
  'passengers': '6',
  'cargo_capacity': '100000',
  'consumables': '2 months',
  'hyperdrive_rating': '0.5',
  'MGLT': '75',
  'starship_class': 'Light freighter',
  'pilots': ['https://swapi.dev/api/people/13/',
   'https://swapi.dev/api/people/14/',
   'https://swapi.dev/api/people/25/',
   'https://swapi.dev/api/people/31/'],
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/'],
  'created': '2014-12-10T16:59:45.094000Z',
  'edited': '2014-12-20T21:23:49.880000Z',
  'url': 'https://swapi.dev/api/starships/10/'},
 {'name': 'Naboo fighter',
  'model': 'N-1 starfighter',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps',
  'cost_in_credits': '200000',
  'length': '11',
  'max_atmosphering_speed': '1100',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '65',
  'consumables': '7 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/11/',
   'https://swapi.dev/api/people/35/',
   'https://swapi.dev/api/people/60/'],
  'films': ['https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/'],
  'created': '2014-12-19T17:39:17.582000Z',
  'edited': '2014-12-20T21:23:49.917000Z',
  'url': 'https://swapi.dev/api/starships/39/'},
 {'name': 'H-type Nubian yacht',
  'model': 'H-type Nubian yacht',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps',
  'cost_in_credits': 'unknown',
  'length': '47.9',
  'max_atmosphering_speed': '8000',
  'crew': '4',
  'passengers': 'unknown',
  'cargo_capacity': 'unknown',
  'consumables': 'unknown',
  'hyperdrive_rating': '0.9',
  'MGLT': 'unknown',
  'starship_class': 'yacht',
  'pilots': ['https://swapi.dev/api/people/35/'],
  'films': ['https://swapi.dev/api/films/5/'],
  'created': '2014-12-20T17:46:46.847000Z',
  'edited': '2014-12-20T21:23:49.932000Z',
  'url': 'https://swapi.dev/api/starships/49/'},
 {'name': 'Naboo star skiff',
  'model': 'J-type star skiff',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated',
  'cost_in_credits': 'unknown',
  'length': '29.2',
  'max_atmosphering_speed': '1050',
  'crew': '3',
  'passengers': '3',
  'cargo_capacity': 'unknown',
  'consumables': 'unknown',
  'hyperdrive_rating': '0.5',
  'MGLT': 'unknown',
  'starship_class': 'yacht',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/35/'],
  'films': ['https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T19:55:15.396000Z',
  'edited': '2014-12-20T21:23:49.948000Z',
  'url': 'https://swapi.dev/api/starships/64/'},
 {'name': 'Naboo Royal Starship',
  'model': 'J-type 327 Nubian royal starship',
  'manufacturer': 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives',
  'cost_in_credits': 'unknown',
  'length': '76',
  'max_atmosphering_speed': '920',
  'crew': '8',
  'passengers': 'unknown',
  'cargo_capacity': 'unknown',
  'consumables': 'unknown',
  'hyperdrive_rating': '1.8',
  'MGLT': 'unknown',
  'starship_class': 'yacht',
  'pilots': ['https://swapi.dev/api/people/39/'],
  'films': ['https://swapi.dev/api/films/4/'],
  'created': '2014-12-19T17:45:03.506000Z',
  'edited': '2014-12-20T21:23:49.919000Z',
  'url': 'https://swapi.dev/api/starships/40/'},
 {'name': 'Scimitar',
  'model': 'Star Courier',
  'manufacturer': 'Republic Sienar Systems',
  'cost_in_credits': '55000000',
  'length': '26.5',
  'max_atmosphering_speed': '1180',
  'crew': '1',
  'passengers': '6',
  'cargo_capacity': '2500000',
  'consumables': '30 days',
  'hyperdrive_rating': '1.5',
  'MGLT': 'unknown',
  'starship_class': 'Space Transport',
  'pilots': ['https://swapi.dev/api/people/44/'],
  'films': ['https://swapi.dev/api/films/4/'],
  'created': '2014-12-20T09:39:56.116000Z',
  'edited': '2014-12-20T21:23:49.922000Z',
  'url': 'https://swapi.dev/api/starships/41/'},
 {'name': 'Jedi starfighter',
  'model': 'Delta-7 Aethersprite-class interceptor',
  'manufacturer': 'Kuat Systems Engineering',
  'cost_in_credits': '180000',
  'length': '8',
  'max_atmosphering_speed': '1150',
  'crew': '1',
  'passengers': '0',
  'cargo_capacity': '60',
  'consumables': '7 days',
  'hyperdrive_rating': '1.0',
  'MGLT': 'unknown',
  'starship_class': 'Starfighter',
  'pilots': ['https://swapi.dev/api/people/10/',
   'https://swapi.dev/api/people/58/'],
  'films': ['https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'created': '2014-12-20T17:35:23.906000Z',
  'edited': '2014-12-20T21:23:49.930000Z',
  'url': 'https://swapi.dev/api/starships/48/'},
 {'name': 'Naboo fighter',

In [39]:
starships_df = pd.DataFrame(starships_df) #turns list into df

In [40]:
starships_df

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
1,Imperial shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,240000,20,850,6,20,80000,2 months,1.0,50,Armed government transport,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T13:04:47.235000Z,2014-12-20T21:23:49.900000Z,https://swapi.dev/api/starships/22/
2,TIE Advanced x1,Twin Ion Engine Advanced x1,Sienar Fleet Systems,unknown,9.2,1200,1,0,150,5 days,1.0,105,Starfighter,[https://swapi.dev/api/people/4/],[https://swapi.dev/api/films/1/],2014-12-12T11:21:32.991000Z,2014-12-20T21:23:49.889000Z,https://swapi.dev/api/starships/13/
3,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
4,Jedi starfighter,Delta-7 Aethersprite-class interceptor,Kuat Systems Engineering,180000,8,1150,1,0,60,7 days,1.0,unknown,Starfighter,"[https://swapi.dev/api/people/10/, https://swa...","[https://swapi.dev/api/films/5/, https://swapi...",2014-12-20T17:35:23.906000Z,2014-12-20T21:23:49.930000Z,https://swapi.dev/api/starships/48/
5,Trade Federation cruiser,Providence-class carrier/destroyer,"Rendili StarDrive, Free Dac Volunteers Enginee...",125000000,1088,1050,600,48247,50000000,4 years,1.5,unknown,capital ship,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:40:21.902000Z,2014-12-20T21:23:49.941000Z,https://swapi.dev/api/starships/59/
6,Naboo star skiff,J-type star skiff,Theed Palace Space Vessel Engineering Corps/Nu...,unknown,29.2,1050,3,3,unknown,unknown,0.5,unknown,yacht,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:55:15.396000Z,2014-12-20T21:23:49.948000Z,https://swapi.dev/api/starships/64/
7,Jedi Interceptor,Eta-2 Actis-class light interceptor,Kuat Systems Engineering,320000,5.47,1500,1,0,60,2 days,1.0,unknown,starfighter,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:56:57.468000Z,2014-12-20T21:23:49.951000Z,https://swapi.dev/api/starships/65/
8,Belbullab-22 starfighter,Belbullab-22 starfighter,Feethan Ottraw Scalable Assemblies,168000,6.71,1100,1,0,140,7 days,6,unknown,starfighter,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T20:38:05.031000Z,2014-12-20T21:23:49.959000Z,https://swapi.dev/api/starships/74/
9,Naboo fighter,N-1 starfighter,Theed Palace Space Vessel Engineering Corps,200000,11,1100,1,0,65,7 days,1.0,unknown,Starfighter,"[https://swapi.dev/api/people/11/, https://swa...","[https://swapi.dev/api/films/4/, https://swapi...",2014-12-19T17:39:17.582000Z,2014-12-20T21:23:49.917000Z,https://swapi.dev/api/starships/39/
10,Trade Federation cruiser,Providence-class carrier/destroyer,"Rendili StarDrive, Free Dac Volunteers Enginee...",125000000,1088,1050,600,48247,50000000,4 years,1.5,unknown,capital ship,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:40:21.902000Z,2014-12-20T21:23:49.941000Z,https://swapi.dev/api/starships/59/
11,Jedi Interceptor,Eta-2 Actis-class light interceptor,Kuat Systems Engineering,320000,5.47,1500,1,0,60,2 days,1.0,unknown,starfighter,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:56:57.468000Z,2014-12-20T21:23:49.951000Z,https://swapi.dev/api/starships/65/
12,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
13,Imperial shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,240000,20,850,6,20,80000,2 months,1.0,50,Armed government transport,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T13:04:47.235000Z,2014-12-20T21:23:49.900000Z,https://swapi.dev/api/starships/22/
14,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
15,Imperial shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,240000,20,850,6,20,80000,2 months,1.0,50,Armed government transport,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T13:04:47.235000Z,2014-12-20T21:23:49.900000Z,https://swapi.dev/api/starships/22/
16,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
17,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/
18,Slave 1,Firespray-31-class patrol and attack,Kuat Systems Engineering,unknown,21.5,1000,1,6,70000,1 month,3.0,70,Patrol craft,[https://swapi.dev/api/people/22/],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T13:00:56.332000Z,2014-12-20T21:23:49.897000Z,https://swapi.dev/api/starships/21/
19,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
20,A-wing,RZ-1 A-wing Interceptor,"Alliance Underground Engineering, Incom Corpor...",175000,9.6,1300,1,0,40,1 week,1.0,120,Starfighter,[https://swapi.dev/api/people/29/],[https://swapi.dev/api/films/3/],2014-12-18T11:16:34.542000Z,2014-12-20T21:23:49.907000Z,https://swapi.dev/api/starships/28/
21,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
22,Naboo fighter,N-1 starfighter,Theed Palace Space Vessel Engineering Corps,200000,11,1100,1,0,65,7 days,1.0,unknown,Starfighter,"[https://swapi.dev/api/people/11/, https://swa...","[https://swapi.dev/api/films/4/, https://swapi...",2014-12-19T17:39:17.582000Z,2014-12-20T21:23:49.917000Z,https://swapi.dev/api/starships/39/
23,H-type Nubian yacht,H-type Nubian yacht,Theed Palace Space Vessel Engineering Corps,unknown,47.9,8000,4,unknown,unknown,unknown,0.9,unknown,yacht,[https://swapi.dev/api/people/35/],[https://swapi.dev/api/films/5/],2014-12-20T17:46:46.847000Z,2014-12-20T21:23:49.932000Z,https://swapi.dev/api/starships/49/
24,Naboo star skiff,J-type star skiff,Theed Palace Space Vessel Engineering Corps/Nu...,unknown,29.2,1050,3,3,unknown,unknown,0.5,unknown,yacht,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T19:55:15.396000Z,2014-12-20T21:23:49.948000Z,https://swapi.dev/api/starships/64/
25,Naboo Royal Starship,J-type 327 Nubian royal starship,"Theed Palace Space Vessel Engineering Corps, N...",unknown,76,920,8,unknown,unknown,unknown,1.8,unknown,yacht,[https://swapi.dev/api/people/39/],[https://swapi.dev/api/films/4/],2014-12-19T17:45:03.506000Z,2014-12-20T21:23:49.919000Z,https://swapi.dev/api/starships/40/
26,Scimitar,Star Courier,Republic Sienar Systems,55000000,26.5,1180,1,6,2500000,30 days,1.5,unknown,Space Transport,[https://swapi.dev/api/people/44/],[https://swapi.dev/api/films/4/],2014-12-20T09:39:56.116000Z,2014-12-20T21:23:49.922000Z,https://swapi.dev/api/starships/41/
27,Jedi starfighter,Delta-7 Aethersprite-class interceptor,Kuat Systems Engineering,180000,8,1150,1,0,60,7 days,1.0,unknown,Starfighter,"[https://swapi.dev/api/people/10/, https://swa...","[https://swapi.dev/api/films/5/, https://swapi...",2014-12-20T17:35:23.906000Z,2014-12-20T21:23:49.930000Z,https://swapi.dev/api/starships/48/
28,Naboo fighter,N-1 starfighter,Theed Palace Space Vessel Engineering Corps,200000,11,1100,1,0,65,7 days,1.0,unknown,Starfighter,"[https://swapi.dev/api/people/11/, https://swa...","[https://swapi.dev/api/films/4/, https://swapi...",2014-12-19T17:39:17.582000Z,2014-12-20T21:23:49.917000Z,https://swapi.dev/api/starships/39/
29,Belbullab-22 starfighter,Belbullab-22 starfighter,Feethan Ottraw Scalable Assemblies,168000,6.71,1100,1,0,140,7 days,6,unknown,starfighter,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-20T20:38:05.031000Z,2014-12-20T21:23:49.959000Z,https://swapi.dev/api/starships/74/

### above work was not necessarily needed

# 2 do the same thing but for planets.

In [41]:
#request planets api
response = requests.get('https://swapi.dev/api/planets/')
data = response.json()

#turn 'data' within the json into a dataframe
planet_df = pd.DataFrame(data['results'])

In [42]:
while data['next'] != None:
    print(data['next'])
    response = requests.get(data['next'])
    data = response.json()
    planet_df = pd.concat([planet_df, pd.DataFrame(data['results'])], ignore_index=True)

https://swapi.dev/api/planets/?page=2
https://swapi.dev/api/planets/?page=3
https://swapi.dev/api/planets/?page=4
https://swapi.dev/api/planets/?page=5
https://swapi.dev/api/planets/?page=6

In [43]:
planet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             60 non-null     object
 1   rotation_period  60 non-null     object
 2   orbital_period   60 non-null     object
 3   diameter         60 non-null     object
 4   climate          60 non-null     object
 5   gravity          60 non-null     object
 6   terrain          60 non-null     object
 7   surface_water    60 non-null     object
 8   population       60 non-null     object
 9   residents        60 non-null     object
 10  films            60 non-null     object
 11  created          60 non-null     object
 12  edited           60 non-null     object
 13  url              60 non-null     object
dtypes: object(14)
memory usage: 6.7+ KB

# number 3

In [44]:

#request starships api
response = requests.get('https://swapi.dev/api/starships/')
data = response.json()

#turn that into a dataframe
starships_df = pd.DataFrame(data['results'])
#take a look
starships_df.info()
starships_df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    10 non-null     object
 1   model                   10 non-null     object
 2   manufacturer            10 non-null     object
 3   cost_in_credits         10 non-null     object
 4   length                  10 non-null     object
 5   max_atmosphering_speed  10 non-null     object
 6   crew                    10 non-null     object
 7   passengers              10 non-null     object
 8   cargo_capacity          10 non-null     object
 9   consumables             10 non-null     object
 10  hyperdrive_rating       10 non-null     object
 11  MGLT                    10 non-null     object
 12  starship_class          10 non-null     object
 13  pilots                  10 non-null     object
 14  films                   10 non-null     object
 15  created                 10 non-null     object
 16  edited                  10 non-null     object
 17  url                     10 non-null     object
dtypes: object(18)
memory usage: 1.5+ KB

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/

In [45]:
while data['next'] != None:
    print(data['next'])
    response = requests.get(data['next'])
    data = response.json()
    starships_df = pd.concat([starships_df, pd.DataFrame(data['results'])], ignore_index=True)

https://swapi.dev/api/starships/?page=2
https://swapi.dev/api/starships/?page=3
https://swapi.dev/api/starships/?page=4

In [46]:
starships_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    36 non-null     object
 1   model                   36 non-null     object
 2   manufacturer            36 non-null     object
 3   cost_in_credits         36 non-null     object
 4   length                  36 non-null     object
 5   max_atmosphering_speed  36 non-null     object
 6   crew                    36 non-null     object
 7   passengers              36 non-null     object
 8   cargo_capacity          36 non-null     object
 9   consumables             36 non-null     object
 10  hyperdrive_rating       36 non-null     object
 11  MGLT                    36 non-null     object
 12  starship_class          36 non-null     object
 13  pilots                  36 non-null     object
 14  films                   36 non-null     object
 15  created                 36 non-null     object
 16  edited                  36 non-null     object
 17  url                     36 non-null     object
dtypes: object(18)
memory usage: 5.2+ KB

# number 4

In [49]:
starship = acquire.get_starships_data()
starship.head(3)

https://swapi.dev/api/starships/?page=2
https://swapi.dev/api/starships/?page=3
https://swapi.dev/api/starships/?page=4

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/

In [50]:
people = acquire.get_people_data()
people.head(3)

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",[],"['https://swapi.dev/api/vehicles/14/', 'https:...","['https://swapi.dev/api/starships/12/', 'https...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,NaN,gold,yellow,112BBY,NaN,https://swapi.dev/api/planets/1/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,NaN,"white, blue",red,33BBY,NaN,https://swapi.dev/api/planets/8/,"['https://swapi.dev/api/films/1/', 'https://sw...",['https://swapi.dev/api/species/2/'],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/

In [51]:
planet = acquire.get_planet_data()
planet.sample(3)

https://swapi.dev/api/planets/?page=2
https://swapi.dev/api/planets/?page=3
https://swapi.dev/api/planets/?page=4
https://swapi.dev/api/planets/?page=5
https://swapi.dev/api/planets/?page=6

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
20,Eriadu,24,360,13490,polluted,1 standard,cityscape,unknown,22000000000,[https://swapi.dev/api/people/12/],[],2014-12-10T16:26:54.384000Z,2014-12-20T20:58:18.454000Z,https://swapi.dev/api/planets/21/
44,Iridonia,29,413,unknown,unknown,unknown,"rocky canyons, acid pools",unknown,unknown,[https://swapi.dev/api/people/54/],[],2014-12-20T10:26:05.788000Z,2014-12-20T20:58:18.497000Z,https://swapi.dev/api/planets/45/
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/

In [52]:
starplanet_df = pd.concat([starships_df, planet_df], axis = 0)
starplanet_df.head(3)

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,...,url,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,...,https://swapi.dev/api/starships/2/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,...,https://swapi.dev/api/starships/3/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,...,https://swapi.dev/api/starships/5/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
ugly_df = pd.concat([starplanet_df, people], axis=0)
ugly_df.head(3)

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,...,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species,vehicles,starships
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
ugly_df.to_csv('starwars.csv')